[package]
name = "broker-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
broker-protocol = { workspace = true }
broker-config = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ldap3 = "0.12"
native-tls = "0.2"
kerberos-parser = "0.9"
der-parser = "10"
ring = "0.17"
nom = "7"
picky-krb = "0.12"
picky-asn1 = { version = "0.10", features = ["time_conversion"] }
picky-asn1-der = "0.5"
time = "0.3"

[dev-dependencies]
tokio = { workspace = true }
yamldap = "0.2"
tempfile = "3"
