[package]
name = "broker-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "indramqtt"
path = "src/main.rs"

[[test]]
name = "e2e_integration"
path = "../../tests/e2e_integration.rs"

[[test]]
name = "soak_chaos_suite"
path = "../../tests/soak_chaos_suite.rs"

[dependencies]
brokerlink = { workspace = true }
broker-protocol = { workspace = true }
broker-router = { workspace = true }
broker-session = { workspace = true }
broker-storage = { workspace = true }
broker-auth = { workspace = true }
broker-config = { workspace = true }
broker-rules = { workspace = true }
broker-connectors = { workspace = true }
broker-cluster = { workspace = true }
broker-api = { workspace = true }
broker-observability = { workspace = true }
broker-gateway = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
flate2 = { workspace = true }
