[package]
name = "broker-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "indramqtt"
path = "src/main.rs"

[dependencies]
brokerlink = { workspace = true }
broker-protocol = { workspace = true }
broker-router = { workspace = true }
broker-session = { workspace = true }
broker-storage = { workspace = true }
broker-auth = { workspace = true }
broker-rules = { workspace = true }
broker-connectors = { workspace = true }
broker-cluster = { workspace = true }
broker-api = { workspace = true }
broker-observability = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
