[package]
name = "broker-connectors"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
broker-protocol = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
md-5 = { workspace = true }
sha1 = { workspace = true }
base64 = { workspace = true }
flate2 = { workspace = true }
uuid = { workspace = true }
jsonwebtoken = { workspace = true }
rsa = { workspace = true }
rand = { workspace = true }
rustls = { version = "0.23.45" }
tokio-rustls = { version = "0.26" }
rustls-pemfile = { version = "1" }
rustls-pki-types = { version = "1" }
rustls-native-certs = { version = "0.8" }
webpki-roots = { version = "0.25" }
tokio-postgres = { version = "0.7" }
tokio-postgres-rustls = { version = "0.14", features = ["native-certs"] }
google-cloud-auth = { version = "1" }
gcp-bigquery-client = { version = "0.28", default-features = false, features = ["native-tls", "aws-lc-rs"] }
scylla = { version = "1.9" }
clickhouse = { version = "0.15", features = ["native-tls"] }
aws-sigv4 = { version = "1" }
futures = { workspace = true }
rdkafka = { version = "0.39", features = ["ssl"] }
schema-registry-client = { version = "0.4" }

[dev-dependencies]
axum = { workspace = true }
apache-avro = { version = "0.15" }
