[package]
name = "broker-connectors"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
broker-protocol = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
sha2 = { workspace = true }
md-5 = { workspace = true }
sha1 = { workspace = true }
base64 = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
